# Generated by Django 3.2.16 on 2025-03-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='title',
        ),
    ]
